### ISSUE TITLE
无效token

### ISSUE THREAD

**Issue by LotingSYR** [PairZhu/ChatGPT-QQRobot#2]
无效的token：Error: ChatGPT failed to refresh auth token. Error: 403 Forbidden

**Comment by PairZhu** [comment]
我用的api包的版本已经失效了，api的原作者似乎已经解决了原问题，等我有空就对接上新的api接口

**Comment by PairZhu** [comment]
我试了一下，新版的还是不太有效，cloudflare的认证那一步就会直接出错。看样子是暂时还是用不了。

**Comment by LotingSYR** [comment]
> 
好像现在需要三个api了

**Comment by LotingSYR** [comment]
这一篇看到的 https://github.com/ashinnotfound/ChatGPT-QQRobot

**Comment by PairZhu** [comment]
这个项目用的接口和我用的不一样。我项目的依赖包作者似乎还没有解决cloudflare的问题

**Comment by PairZhu** [comment]
看了一眼源码，似乎解决了，但是文档还没改好（，等我忙完这段时间再研究吧

**Comment by LotingSYR** [comment]
希望尽快解决一下，也不知道这次的方法还能用多久😶‍🌫️

**Comment by PairZhu** [comment]
现在这就是猫捉耗子的游戏。而且官方指不定过几天就彻底关了，不免费开放了呢。所以说随缘喽，不要放太多精力在这上面。毕竟都是依赖于人家的服务的，不是本地服务不靠谱。有这精力不如看点能本地运行的项目

**Comment by LotingSYR** [comment]
哎，这也是没办法，谁让openai最会讲话，大家都爱这玩意，api又贵死。(ˉ﹃ˉ)

**Comment by PairZhu** [comment]
其实这个插件的作用我觉得就只是群里开猫娘yin趴用的（。毕竟注册成本很低

**Comment by LotingSYR** [comment]
包括但是不限于，它涵盖的东西很多，虽然欺负ai猫娘确实很好玩（

**Comment by PairZhu** [comment]
不，其它用途你完全可以自己注册账号，直接在网站上用啊

**Comment by LotingSYR** [comment]
惠及群友（

**Comment by PairZhu** [comment]
不如把注册教程发给群友

**Comment by LotingSYR** [comment]
问题是qq直接聊才方便
